services:
  db:
    image: mysql:8.0
    container_name: fms-db
    restart: always
    environment:
      MYSQL_DATABASE: fms_backend_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fmsuser
      MYSQL_PASSWORD: fmspass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fms-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fms-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fms_backend_db
      SPRING_DATASOURCE_USERNAME: fmsuser
      SPRING_DATASOURCE_PASSWORD: fmspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8082:8080"
    networks:
      - fms-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fms-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - fms-net

  nginx:
    image: nginx:latest
    container_name: fms-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - fms-net

volumes:
  db_data:

networks:
  fms-net:
    driver: bridge
